""" App Config """

DEBUG = True #Keep on for debugging during development
SQLALCHEMY_DATABASE_URI = 'TODO'
SECRET_KEY = 'THISISABIGSECRET'
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
